events {}

http {
  upstream collabhub_gateways {
    least_conn;
    server gateway-1:7000;
    server gateway-2:7000;
  }

  server {
    listen 7000;
    client_max_body_size 128k;

    location / {
      proxy_pass http://collabhub_gateways;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 75s;
      proxy_send_timeout 10s;
    }
  }
}
